# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0083992c7aaddd4b0d9e444db35f3a5f09721278918d1bb09482a646f363b3b29f3f212ac6c8ff92cc861d6a56599a506781d591b55bbc2c936e4027f1dba9e8

test:
  secret_key_base: cea46cf49af3b5882dbd2eb02123e0b5d8c0bb2597892b74e3c0f9792c739997eaf3d64f545a5fd8ec6b37f2827a06a4d49389d6844b7eb4224d77bed321c412

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
